server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com       #eureka服务端的实例名称   单机版 hostname: localhost    集群版hostname: eureka7001.com
  client:
    register-with-eureka:  false  #false表示不向注册中心注册自己
    fetch-registry: false
    service-url:                #单机版  http://${eureka.instance.hostname}:${server.port}/eureka/
      #defaultZone: http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/

